# Gauss-Seidel Method
## An iterative approach to solve a system of linear equations AX = B

### NOTE: 
#####           1. The diagonal elements of A must be non-zero
#####            2. The convergence to the true solution is guaranteed when the matrix A is either strictly diagonally dominant or   symmetric and positive definite.

In [2]:
import numpy as np #using numpy library for working  with arrays

In [4]:
n = int(input("\nEnter the number of unknowns: ")) #taking input from the user for no. of unknowns, i.e., the value of n
a = 1

A = np.zeros((n,n)) #initialize a matrix A of order (n x n)
B = np.zeros((n,a)) #initialize a column matrix B of order (n x 1)

X = np.zeros((n,a)) #initialize a solution vector


Enter the number of unknowns: 2


###### Taking input from the user for matrix A

In [5]:
print("\nEnter the elements of matrix A: ")

for i in range(n):
    for j in range(n):
        A[i][j] = float(input( "A["+str(i+1)+']['+str(j+1)+"] = "))


print("\nThe matrix [A] = ")
                        
for i in range(n):
    for j in range(n):
        print( A[i][j], end=" ")
    print()



Enter the elements of matrix A: 
A[1][1] = 1
A[1][2] = -5
A[2][1] = 7
A[2][2] = 1

The matrix [A] = 
1.0 -5.0 
7.0 1.0 


###### Taking input from the user for column matrix B

In [6]:
print("\nEnter elements of the matrix B: ")

for i in range(n):
    for j in range(a):
        B[i][j] = float(input( "B["+str(i+1)+']['+str(1)+"] = "))

print("\nThe matrix [B] = ")

for i in range(n):
    for j in range(a):
        print( B[i][j], end=" ")
    print()


Enter elements of the matrix B: 
B[1][1] = -4
B[2][1] = 6

The matrix [B] = 
-4.0 
6.0 


<span style="color: red;">At first, we need to investigate whether the matrix A is diagonally dominant or not, in order to show if the 'X' vector is converging to the actual solution.</span>
 

In [8]:
flag = 1

for i in range(n):
    s=0 #initializing the sum of elements of rows excluding the diagonal row element
    for j in range(n):
        if (i!=j):
            s=s+ abs(A[i][j]) #adding elements to the sum
            
    q = s - abs(A[i][i])  #defining variable to compute the difference between the sum of row elements and the diagonal element
    if q>0:
        flag = 0

if (flag == 0): print ("\nA is not a diagonally dominant matrix.")

else: print("\nA is a diagonally dominant matrix.")


A is not a diagonally dominant matrix.


#### Implementation of the iterative technique

In [10]:
print("\nThe vector after each iteration is given as follows: ")

# After investigation, we implement this iterative technique as follows:
for alpha in range(10):  #iteration range
    for i in range(n):
    
        for k in range(a):
            X[i][k] = B[i][k] #equating the corresponding elements of X and B
        for j in range(n):
            if ( i != j ):
                X[i][a-1] = X[i][a-1] - X[j][a-1]*A[i][j] #using the expression of X(k+1)
                            
        X[i][0] /= A[i][i] #divide by A(i,i)
        X[i][0] = round(X[i][0], 6)

    print("\n\n",'Iteration No.'+str(alpha+1),":\n", X)

if (flag==1): print('The vector X will eventually converge to the actual solution.')
else: print('\n\nThe vector X will then diverge from the actual solution.')


The vector after each iteration is given as follows: 


 Iteration No.1 :
 [[ 2.48019966e+08]
 [-1.73613976e+09]]


 Iteration No.2 :
 [[-8.68069878e+09]
 [ 6.07648915e+10]]


 Iteration No.3 :
 [[ 3.03824457e+11]
 [-2.12677120e+12]]


 Iteration No.4 :
 [[-1.06338560e+13]
 [ 7.44369921e+13]]


 Iteration No.5 :
 [[ 3.72184960e+14]
 [-2.60529472e+15]]


 Iteration No.6 :
 [[-1.30264736e+16]
 [ 9.11853153e+16]]


 Iteration No.7 :
 [[ 4.55926576e+17]
 [-3.19148604e+18]]


 Iteration No.8 :
 [[-1.59574302e+19]
 [ 1.11702011e+20]]


 Iteration No.9 :
 [[ 5.58510056e+20]
 [-3.90957039e+21]]


 Iteration No.10 :
 [[-1.95478520e+22]
 [ 1.36834964e+23]]


The vector X will then diverge from the actual solution.
